//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emppj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int payrollitem { get; set; }
        public string itemtype { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> value { get; set; }
    }
}
